version: '3'
services:

  redis:
    image: grokzen/redis-cluster:latest
    ports:
      - 7000:7000
  redis-test:
    build: ./
    depends_on:
      - redis
    environment:
      host: redis
      port: 7000
